# Generated by ChatGPT, but license to you remains the same as the repo.

$path = "\\NetworkDrive\Folder1\Folder 2"

$imageExt = ".jpg",".jpeg",".png",".gif",".bmp",".tiff",".webp",".heic"
$videoExt = ".mp4",".mov",".avi",".mkv",".wmv",".flv",".webm",".mpeg",".mpg",".m4v"

$imageCount = 0
$videoCount = 0

Get-ChildItem $path -Recurse -File -ErrorAction SilentlyContinue | ForEach-Object {
    $ext = $_.Extension.ToLower()
    if ($imageExt -contains $ext) { $imageCount++ }
    elseif ($videoExt -contains $ext) { $videoCount++ }
}

[PSCustomObject]@{
    ImageCount = $imageCount
    VideoCount = $videoCount
}