# STATUS_TABLE_NAME = "status"
# STATUS_TABLE_VERSION_FIELD = "app_version"
# STATUS_TABLE_SOURCE_PATH_FIELD = "root_source_path"
# STATUS_TABLE_TARGET_PATH_FIELD = "root_target_path"
# STATUS_TABLE_FOLLOW_SYMLINKS_FIELD = "follow_symlinks"
# STATUS_TABLE_COMPLETE_FIELD = "complete"
# STATUS_TABLE_STARTED_FIELD = "started"
# STATUS_TABLE_ID_FIELD = "id"
#
# SOURCE_FILES_TABLE_NAME = "source_files"
# TARGET_FILES_TABLE_NAME = "target_files"
# FILES_TABLES_ID_FIELD = "id"
# FILES_TABLES_HASH_FIELD = "hash"
# FILES_TABLES_PATH_FIELD = "path"
#
# TIMESTAMP_TIME_FORMAT = "%Y-%m-%d %H:%M:%S"

APP_VERSION_MAJOR = 1
APP_VERSION_MINOR = 0
APP_VERSION_PATCH = 0

DEFAULT_DB_FILE_NAME = "../../old/data_cache"

SHA_256_SUM_EMPTY_FILE_HASH = b"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"